修复很多东西
project-mirai/mirai-api-http pull request #287
Opened 2021-03-21 17:03 UTC by HoshinoTented

* 修复 typo （breaking changes）
* 修复部分情况下导致的错误序列化 IgnoreDTOEvent（同时保险起见，为 IgnoreDTOEvent 添加序列化）

2021-03-21 17:05 UTC, HoshinoTented commented
需要注意的是，关于 peekMessage 的那部分代码没有经过完整测试，希望作为 dev 版本发布

2021-03-21 22:56 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/queue/MessageQueue.kt
> +        while (iter.hasNext()) {
```
for (dto in itr)
```

Maybe better

2021-03-22 01:34 UTC, ryoii commented
`IgnoreDTO` 不应该被序列化，在错误调用的地方把它过滤掉

2021-03-22 04:03 UTC, HoshinoTented commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/queue/MessageQueue.kt
> +        while (iter.hasNext()) {
got it

2021-03-22 04:03 UTC, HoshinoTented commented
> `IgnoreDTO` 不应该被序列化，在错误调用的地方把它过滤掉

但是有某些 sabee 就序列化了

2021-03-22 05:06 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/queue/MessageQueue.kt
>      }
```kotlin
asSequence().map { it.toDTO() }.filter { it !== IgnoreEventDTO }.take(size).toList()
```

2021-03-22 06:12 UTC, HoshinoTented commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/queue/MessageQueue.kt
>      }
好的，我是大傻逼

2021-03-22 15:50 UTC, HoshinoTented commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/queue/MessageQueue.kt
>      }
我不会改

2021-03-23 07:14 UTC, HoshinoTented commented
这些代码完全没有经过测试，谨慎 merge

2021-03-23 11:57 UTC, Him188 requested changes

2021-03-23 11:57 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        miraiGet("/peekMessage") {
我建议再加一个 `miraiGet("/peakMessage")` 来调用 "/peekMessage" (将实现提取为一个 fun 然后由这两个 route 调用) 来兼容旧版本

2021-03-23 11:58 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        miraiGet("/peekMessage") {
文档可以直接修改, 但隐式保留对以前的支持

2021-03-23 14:33 UTC, HoshinoTented commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        miraiGet("/peekMessage") {
哦对的，我本来有想到这个，但是忘了

2021-03-23 14:33 UTC, HoshinoTented commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        miraiGet("/peekMessage") {
现在加

2021-03-23 14:40 UTC, Karlatemp approved these changes

2021-03-26 07:32 UTC, HoshinoTented commented
review 一下求求
全部 approve 之后我再 merge

2021-03-26 07:45 UTC, Him188 approved these changes

2021-03-26 07:46 UTC, Him188 commented
@ryoii

2021-03-26 07:48 UTC, HoshinoTented commented
no need for yellow's approvement

2021-03-26 07:48 UTC, merged