加入戳一戳识别
project-mirai/mirai-api-http pull request #288
Opened 2021-03-22 09:08 UTC by Doctor-Yin

2021-03-22 09:14 UTC, Karlatemp requested changes

2021-03-22 09:14 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +}
DTO 不要出现 var
```suggestion
@Serializable
data class SubjectTDO(
    override val id: Long,
    val environment: String
) : ContactDTO() {
    constructor(contact: Contact) : this(contact.id, when (contact) {
        is Friend -> this.environment = "Friend"
        is Group -> this.environment = "Group"
        is Stranger -> this.environment = "Stranger"
        is OtherClient -> this.environment = "OtherClient"
    })
}
```

2021-03-22 09:14 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
>  }
TODO 删了, 以及请在 pr 标题中说明也进行了 remark 相关的修改

2021-03-22 09:15 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +}
`DTO` not `TDO`

2021-03-22 09:17 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +}
.....

2021-03-22 10:54 UTC, Him188 requested changes

2021-03-22 10:54 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class UserOrBotTDO(
应是 DTO

2021-03-22 10:54 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class SubjectTDO(
应是 DTO

2021-03-22 10:54 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +    val environment: String
我推荐叫 `kind`，`environment` 似乎不太恰当

2021-03-22 10:54 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class UserOrBotTDO(
#为什么 `SubjectDTO` 有 `environment` 属性，而 `UserOrBotDTO` 没有呢？是故意为之还是漏了

2021-03-22 10:58 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class UserOrBotTDO(
用于判断戳一戳环境的

2021-03-22 11:00 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +    val environment: String
感觉上都差不多，戳一戳是在群/好友环境下的

2021-03-22 12:25 UTC, Doctor-Yin commented
添加戳一戳发送

2021-03-22 13:29 UTC, Doctor-Yin commented
#279

2021-03-23 10:35 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> + */
```suggestion
/**
 * 戳一戳发送
 */
```

2021-03-23 10:35 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +}
Use `IllegalArgumentException` instead

2021-03-23 10:35 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +}
Use `IllegalArgumentException` instead of `IllegalAccessException`

2021-03-23 10:35 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +                }
```suggestion
                "Friend" -> {
                    dto.session.bot.let { bot -> bot.getFriendOrFailed(dto.target).nudge().sendTo(bot.getFriendOrFailed(dto.subject)) }
                }
```

2021-03-23 12:05 UTC, Him188 commented
请在一个 PR 中只处理一个问题, 以方便代码管理

2021-03-23 15:38 UTC, Him188 requested changes

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +            else -> "OtherClient"
能判断类型就应该避免 `else`，保证兼容性

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class UserOrBotDTO(
`UserOrBotDTO` 没有必要，使用 `QQDto` 也一样

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +    val environment: String
此时更适用 `kind` 或 `type`，由于 `type` 被序列化保留故使用 `kind`。在 core 中也有命名为 `kind` 的属性。

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/BotEventDTO.kt
> +    val from: UserOrBotDTO,
根据现有事件命名，应该叫 `fromId`，下同

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/BotEventDTO.kt
> +    val from: UserOrBotDTO,
或者，（我更倾向于）参照[以前的实现方案](https://github.com/project-mirai/mirai-api-http/blob/master/docs/EventType.md#%E6%88%90%E5%91%98%E8%A2%AB%E8%B8%A2%E5%87%BA%E7%BE%A4%E8%AF%A5%E6%88%90%E5%91%98%E4%B8%8D%E6%98%AFbot)，将用户对象序列化部分信息。

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +data class SubjectDTO(
Subjct 本质上是一个 Contact，可能用带类型的多态序列化更好（@ryoii ）

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +    val environment: String
environment 同上，可能改叫 subjectType 或 subjectKind，取决于上面的修改

2021-03-23 15:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +                else -> throw IllegalArgumentException("戳一戳类型不存在")
异常中说明传来的类型具体是什么，附加 `dto.environment`

2021-03-23 15:39 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +            else -> "OtherClient"
idea爆红。。。。

2021-03-23 15:42 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +            else -> "OtherClient"
else -> error("Not in support")

2021-03-23 16:40 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/BotEventDTO.kt
> +    val from: UserOrBotDTO,
只有一个类型和id，可以不用序列化吧

2021-03-23 16:41 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/ContactDTO.kt
> +    val environment: String
使用了kind

2021-03-24 08:45 UTC, Him188 requested changes

2021-03-24 08:45 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
> +    nudgeModule()
应该放在 `messageModule` 而不是独立一个

2021-03-24 08:45 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/NudgeModule.kt
> +                else -> throw IllegalArgumentException("戳一戳类型${dto.kind}不存在")
英文单词和中文之间添加空格
```suggestion
                else -> throw IllegalArgumentException("戳一戳类型 ${dto.kind} 不存在")
```

2021-03-24 09:16 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
> +    nudgeModule()
我认为独立出来是合理的，core里nudge与message也是分开的

2021-03-25 03:16 UTC, Doctor-Yin commented
>

2021-03-25 14:38 UTC, Karlatemp approved these changes

2021-03-26 09:05 UTC, merged