加入文件操作
project-mirai/mirai-api-http pull request #294
Opened 2021-03-27 08:17 UTC by Doctor-Yin

2021-03-27 10:28 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
> +        String::class -> call.parameters[name].orEmpty()
这会改变全局的行为? 是否有影响以前的功能? 我不建议进行这个修改

2021-03-27 10:28 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +                        RemoteFileDTO(remoteFile, remoteFile.isFile())
`RemoteFile.isFile` 会查询一次文件的详细信息 `FileInfo` 并获取其中 `FileInfo.isFile`, 此时返回详细的文件信息(`FileInfoDTO`)是否更方便?

2021-03-27 10:31 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
> +        String::class -> call.parameters[name].orEmpty()
目录选项是可选类型，可能是空

2021-03-27 10:33 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
> +        String::class -> call.parameters[name].orEmpty()
这里修改的是 BaseRoute 会影响所有以前的功能, 因此这个修改有可能会产生一些意想不到的错误

2021-03-27 11:36 UTC, Karlatemp requested changes

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/FileDTO.kt
> +    val type: String
直接 `val isFile: Boolean`, `val type: String` 闲的多余

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/FileDTO.kt
> +}
此类显的多余

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
>          !path.isNullOrBlank() -> with(HttpApiPluginBase.voice(path)) {
PR 中不要附带其他无关修改, 可以在最后还原

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
>          UInt::class -> call.parameters[name]?.toUInt()
PR 中不要附带其他无关修改

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +        }
根据 Kotlin 风格，除短且简单的 lambda 外， 始终应该显式声明参数，且不应该与默认的 it 一致

https://www.kotlincn.net/docs/reference/coding-conventions.html#lambda-%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%8F%82%E6%95%B0

2021-03-27 11:36 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +        }
多余操作符 `throw`

2021-03-27 11:37 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/FileDTO.kt
> +    val type: String
确实....

2021-03-27 11:38 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
>          !path.isNullOrBlank() -> with(HttpApiPluginBase.voice(path)) {
这个我裂开

2021-03-27 11:38 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
>          !path.isNullOrBlank() -> with(HttpApiPluginBase.voice(path)) {
我估计这是因为 Kotlin 官方代码风格变化导致的自动 reformat, 我觉得可以 accept

2021-03-27 11:39 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +        }
emmmmm

2021-03-27 11:40 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +        }
emmmmmm

2021-03-27 11:41 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/BaseRoute.kt
>          UInt::class -> call.parameters[name]?.toUInt()
我又裂开

2021-03-29 10:07 UTC, Him188 requested changes

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +    val type: String
将来 `type` 可能就用于序列化了, 现在可以避免使用

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +                    fileInfo.getDownloadInfo() ?: error("文件ID $id 是一个目录")
这一行会在 `null` 时抛异常, 同样上一行也需要这个做

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +                if (dir.isEmpty()) file.listFiles()
我建议复杂的语句的 `if` 添加大括号

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            parts.file("file")?.apply {
避免大范围转换 receiver.  将它作为普通参数代替

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                        originalFileName ?: generateSessionKey(), it.readBytes()
范围很大的 lambda 避免使用 `it`. 总是定义参数名

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            TODO()
不要抛出 `UnsupportedOperationError`. 可以删除 `miraiVerify<FileCopyTODTO>("/FileCopyTO") `

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +@MiraiExperimentalApi
避免使用实验性 API

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +@MiraiExperimentalApi
如果有必须使用的, 在相应位置使用 `@OptIn`.

2021-03-29 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +@MiraiExperimentalApi
如果有必须使用的, 在相应位置使用 `@OptIn`.

2021-03-29 10:10 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            } ?: throw IllegalAccessException("未知错误")
我也不知道这是啥，从uploadimg复制来的

2021-03-29 10:17 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            } ?: throw IllegalAccessException("未知错误")
那就可以先留着

2021-03-29 10:20 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/InfoRouteModule.kt
> +                if (dir.isEmpty()) file.listFiles()
有大括号.....

2021-03-29 13:38 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            parts.file("file")?.apply {
应该咋改....

2021-03-30 01:16 UTC, Him188 requested changes

2021-03-30 01:16 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                            } else source = newFile.await().sendTo(group, "/$path/${newFile.await().name}").source
应该由调用方决定上传到服务器的文件名。不需要由插件限制必须与本地文件名相同。与 core 保持相同设计

2021-03-30 01:16 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                            } else source = newFile.await().sendTo(group, "/$path/${newFile.await().name}").source
source 仅用于获取 message，那么就可以存储 MessageChain 而不是它里面的 source

chain.source.originalMessage 与 chain 是相同的。见 `MessageSource.Outgoing` 和 `Contact.sendMessage`

2021-03-30 01:16 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            call.respondDTO(UploadFileRetDTO(id = (source.originalMessage.last() as FileMessage).id))
`.last()` 没有兼容性保证，应该使用 `MessageChain.get` 操作。（FileMessage 是 ConstrainSingle）

2021-03-30 01:16 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            file.provider().use { inPutStream ->
inputStream 只在第 107 行使用，那么可以把 `use` 代码块变小让代码逻辑更清晰。
```kotlin
            val newFile = file.provider().use { inPutStream ->
```

2021-03-30 01:16 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                            } else source = newFile.await().sendTo(group, "/$path/${newFile.await().name}").source
可以让 path 属性表示完整远程路径 （RemoteFile.path）那样，然后插件通过字符串 `/` 分隔来创建目录等。
这个路径包含文件名也因此保证了灵活

2021-03-30 13:11 UTC, Him188 requested changes

2021-03-30 13:11 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            call.respondDTO(UploadFileRetDTO(id = (messageChain[FileMessage.topmostKey] as FileMessage).id))
```suggestion
            call.respondDTO(UploadFileRetDTO(id = messageChain[FileMessage].id))
```

2021-03-30 13:15 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            call.respondDTO(UploadFileRetDTO(id = (messageChain[FileMessage.topmostKey] as FileMessage).id))
我这样写idea报错。。。

2021-03-30 13:26 UTC, Him188 approved these changes

2021-03-30 13:26 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            call.respondDTO(UploadFileRetDTO(id = (messageChain[FileMessage.topmostKey] as FileMessage).id))
加个 `!!`

备注: 因为能保证上文消息有 `FileMessage`

2021-03-30 13:26 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                file.originalFileName ?: generateSessionKey(), file.provider().readBytes()
虽然这里 `readBytes()` 来处理文件不好...但这也是历史问题了 @ryoii

2021-03-30 14:54 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            if (file.isFile()) error("文件ID ${dto.id} 是一个目录")
Typo?

2021-03-30 14:54 UTC, Karlatemp commented on docs/API.md
> +| file         | File   | false | -           | 文件              |
```suggestion
| 名字         | 类型   | 可选  | 举例        | 说明                 |
| ------------ | ------ | ----- | ----------- | ----------------- |
| sessionKey   | String | false | YourSession | 已经激活的Session   |
| type         | String | false | "Group"     | 当前仅支持 "Group" |
| path         | String | false | 文件夹/文件名 | 文件上传目录与名字   |
| file         | File   | false | -           | 文件内容          |
```

2021-03-30 14:59 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            if (file.isFile()) error("文件ID ${dto.id} 是一个目录")
应该咋写.......

2021-03-30 15:00 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            if (file.isFile()) error("文件ID ${dto.id} 是一个目录")
前面不用加文件两个字，读着都怪怪的...

2021-03-30 15:03 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            if (file.isFile()) error("文件ID ${dto.id} 是一个目录")
这句可以删掉，是否允许 rename 应该由 core 判断

2021-03-30 15:04 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            if (file.isFile()) error("文件ID ${dto.id} 是一个目录")
ok

2021-03-30 15:12 UTC, Karlatemp reviewed
api.md 少了 groupFileList 和 groupFileInfo

2021-03-30 15:13 UTC, Doctor-Yin commented
我裂开

2021-03-30 17:34 UTC, Him188 requested changes

2021-03-30 17:34 UTC, Him188 commented on README.md
> +    * [校验Session](docs/API.md#校验Session)
避免进行与 '加入文件操作' 无关的修改

2021-04-01 15:20 UTC, Karlatemp approved these changes

2021-04-01 15:22 UTC, Him188 approved these changes

2021-04-02 13:37 UTC, merged