添加支持设置精华消息
project-mirai/mirai-api-http pull request #297
Opened 2021-03-29 14:44 UTC by Doctor-Yin

2021-03-30 01:01 UTC, Him188 requested changes

2021-03-30 01:01 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +private data class RecallAndEssenceDTO(
不应该混合使用

2021-03-30 13:27 UTC, Him188 approved these changes

2021-03-31 14:43 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        }
`setEssenceMessage` 存在返回值, 应该判断返回值类型并决定应该返回 Success / Failed

2021-03-31 14:45 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/MessageRouteModule.kt
> +        }
该判断我没写判断，不判断写一堆判断，裂开

2021-04-01 08:40 UTC, Him188 approved these changes

2021-04-01 11:12 UTC, Doctor-Yin commented
close #264

2021-04-01 11:13 UTC, Doctor-Yin commented
#264

2021-04-01 15:22 UTC, Karlatemp commented on docs/API.md
> +[POST]/setEssence
```suggestion
[POST] /setEssence
```

2021-04-02 08:59 UTC, Karlatemp approved these changes

2021-04-02 09:56 UTC, merged