修复文件上传问题Fix #310 Fix #306 Fix #305
project-mirai/mirai-api-http pull request #311
Opened 2021-04-09 08:18 UTC by Doctor-Yin

2021-04-09 09:09 UTC, Doctor-Yin commented
Fix #307

2021-04-09 09:10 UTC, Doctor-Yin commented
Fix #310 
Fix #308 
Fix #306 
Fix #305

2021-04-09 10:07 UTC, Him188 requested changes

2021-04-09 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                        }
可以修改为 `resolve(path).uploadAndSend(   )`

2021-04-09 10:07 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                        }
创建目录有 side-effect, 应该避免 (由用户自己提前 mkdir)

2021-04-09 13:06 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +        miraiVerify<MkDirDTO>("/groupMkDir") { dto ->
这个不是“修复文件api”，应该在另一个PR

2021-04-09 13:07 UTC, Doctor-Yin commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +        miraiVerify<MkDirDTO>("/groupMkDir") { dto ->
我裂开

2021-04-10 08:06 UTC, Him188 requested changes

2021-04-10 08:06 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +                            ) throw error("文件夹 ${dir.name} 不存在")
不需要判断目录是否存在, 不存在时 `upload` 会抛异常 `IllegalStateException`, 捕获这个异常返回就行了

2021-04-10 08:22 UTC, Him188 requested changes

2021-04-10 08:22 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +    val target: Long
```suggestion
    val group: Long
```

2021-04-10 08:22 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            val dir = dto.session.bot.getGroupOrFail(dto.target).filesRoot.resolve("/${dto.dir}")
如果 dir 带 "/", `resolve` 就会抛异常

2021-04-10 08:22 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +            val dir = dto.session.bot.getGroupOrFail(dto.target).filesRoot.resolve("/${dto.dir}")
在 root 里 resolve, 带不带 "/" 效果都是一样的, 因此没有必要主动加 "/"

2021-04-11 14:00 UTC, Him188 approved these changes

2021-04-11 14:33 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +        miraiVerify<MkDirDTO>("/groupMkDir") { dto ->
按照 `java.io.File` 和 命令行 此处 `groupMkdir` 更好? (指小写)

2021-04-11 14:34 UTC, Karlatemp approved these changes

2021-04-11 14:37 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/route/FileRouteModule.kt
> +        miraiVerify<MkDirDTO>("/groupMkDir") { dto ->
实际请求时应该是忽略大小写的吧, 不过改了更好

2021-04-14 14:45 UTC, Him188 commented on docs/API.md
> +### 重命名群文件/目录
```suggestion
### 创建群文件目录
```

2021-04-14 14:48 UTC, Him188 approved these changes

2021-04-14 15:22 UTC, merged