Add support to MusicShare
project-mirai/mirai-api-http pull request #320
Opened 2021-04-19 15:58 UTC by Yoshino-s

2021-04-19 16:00 UTC, Him188 approved these changes

2021-04-19 16:06 UTC, Karlatemp requested changes

2021-04-19 16:06 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
> +    }
去除 try, 以让参数错误时直接抛出错误

2021-04-19 16:26 UTC, Yoshino-s commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
> +    }
也不是不可以

2021-04-19 16:47 UTC, Him188 approved these changes

2021-04-20 03:21 UTC, Karlatemp commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
> +            MusicShare(MusicKind.valueOf(kind), title, summary, jumpUrl, pictureUrl, musicUrl, brief)
```suggestion
    is MusicShareDTO -> {
        if (brief.isNullOrBlank()) {
            MusicShare(MusicKind.valueOf(kind), title, summary, jumpUrl, pictureUrl, musicUrl)
        } else {
            MusicShare(MusicKind.valueOf(kind), title, summary, jumpUrl, pictureUrl, musicUrl, brief)
        }
    }
```

2021-04-20 03:42 UTC, Him188 commented on mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/data/common/MessageDTO.kt
> +            MusicShare(MusicKind.valueOf(kind), title, summary, jumpUrl, pictureUrl, musicUrl, brief)
我觉得原来的也行，反正不复杂

2021-04-20 04:08 UTC, Karlatemp approved these changes

2021-04-20 04:19 UTC, Him188 commented
@Yoshino-s Thanks!

2021-04-20 04:19 UTC, merged