修改在线文档安装命令与模板不符
project-mirai/mirai-api-http pull request #672
Opened 2023-01-17 10:31 UTC by MR-XieXuan

在 在线文档中添加 V2 版本的安装命令，与模板前提示模板版本号

2023-01-24 12:33 UTC, MR-XieXuan commented
@Him188 可以看一下这个东西咩

2023-01-24 21:31 UTC, Him188 requested changes

2023-01-24 21:31 UTC, Him188 commented on docs/README.md
> +* `MCL` 支持自动更新插件，支持设置插件更新频道等功能
重复了

2023-01-30 11:17 UTC, MR-XieXuan commented
@Him188 OK

2023-02-10 07:23 UTC, ryoii approved these changes

2023-02-10 07:24 UTC, merged